// Generated by https://quicktype.io

export interface AllCitasResponse {
    data: AllCitasArr[];
}

export interface AllCitasArr {
    id:           number;
    uid_manychat: string;
    name:         string;
    phone:        string;
    day:          string;
    hour:         string;
    contacted:    number;
    answer:       number;
    created_at:   string;
    updated_at:   string;
}
