// Generated by https://quicktype.io

export interface CreateCitaRequest {
    uid_manychat: string;
    name:         string;
    phone:        string;
    day:          string;
    hour:         string;
}
